security:
  # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Security\AppLoginAuthenticator
      logout:
        path: app_logout
        # où rediriger après la déconnexion
        target: app_login

      # Ajout de la gestion de la connexion via le formulaire
      form_login:
        login_path: app_login
        check_path: app_login
        default_target_path: /home # Redirection après la connexion réussie par défaut

      # Gestion de la redirection selon le rôle après la connexion
      success_handler: App\Security\AuthenticationSuccessHandler

  # Gestion des règles d'accès (accès aux pages en fonction des rôles)
  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/veterinarian, roles: ROLE_VETERINARIAN }
    - { path: ^/employee, roles: ROLE_EMPLOYEE }
    # Redirection par défaut si aucune règle ne correspond
    - { path: ^/home, roles: ROLE_USER }
