security:
  # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Security\AppLoginAuthenticator
      entry_point: App\Security\AppLoginAuthenticator # Ajout de l'entry_point pour spécifier l'authentificateur
      logout:
        path: app_logout
        target: app_login

  # Gestion des règles d'accès (accès aux pages en fonction des rôles)
  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/veterinarian, roles: ROLE_VETERINAIRE }
    - { path: ^/employee, roles: ROLE_EMPLOYE }
    # Redirection par défaut si aucune règle ne correspond
    - { path: ^/home, roles: ROLE_USER }
