version: "3.8"

services:
  app:
    build: .
    container_name: arcadia_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: arcadia_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: arcadiazoo
      MYSQL_USER: arcadia
      MYSQL_PASSWORD: arcadia123
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: arcadia_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: arcadia
      PMA_PASSWORD: arcadia123
    depends_on:
      - db

volumes:
  db_data:
